export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_CART = 'DELETE_CART';
export const MESSAGE_CART_DELETE = 'MESSAGE_CART_DELETE';
export const UPDATE_CART = 'UPDATE_CART';
export const MESSAGE_UPDATE_CART = 'MESSAGE_UPDATE_CART';